--cleanup file for AlterDatabase.sql
USE master;
GO
ALTER DATABASE AdventureWorks2012
SET READ_WRITE;
GO
ALTER DATABASE AdventureWorks2012
    SET ALLOW_SNAPSHOT_ISOLATION OFF,
	RECOVERY SIMPLE;
GO
ALTER DATABASE AdventureWorks2012
REMOVE FILE Test1dat2;
GO
ALTER DATABASE AdventureWorks2012
REMOVE FILE test1dat3;
GO
ALTER DATABASE AdventureWorks2012
REMOVE FILE test1log2;
GO
ALTER DATABASE AdventureWorks2012
REMOVE FILE test1log3;
GO
ALTER DATABASE AdventureWorks2012
REMOVE FILEGROUP Test1FG1;
GO

